name: LabC

on: [push]
jobs:
  build-and-run:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make build
    - name: run
      run: make run
    - name: clean
      run: make clean
